steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs:latest_build', '-f', 'build/Dockerfile', '.' ]
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --image-url=gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs@latest_build']
timeout: '1600s'