steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs:latest_build -f build/Dockerfile .']
timeout: '1600s'
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'echo $COMMIT_SHA']
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --image-url=gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs@latest_build']
timeout: '1600s'