steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs:$COMMIT_SHA', '-f', 'build/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --image-url=gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs:$COMMIT_SHA --quiet']
timeout: '1600s'
images:
- gcr.io/travelauthorizationpoc/github.com/petr-lysachev-gmail/web_app_vs:$COMMIT_SHA


